### ISSUE TITLE
[ComfyUI] setting画面で設定を行う

### ISSUE THREAD

**Issue by nomadoor** [Taremin/webui-monaco-prompt#3]
ComfyUIで使うとすべての入力欄上に設定がでてきてしまいかなり邪魔です。
メニューのSettingsから設定できるように、かつ設定の保持もできるようになるととても助かります。

[ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)のコードが参考になるかもしれません
e.g. https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/web/js/showImageOnMenu.js

**Comment by Taremin** [comment]
ありがとうございます。
たしかにヘッダが邪魔になっていますね…。
コメントを見る前に 5316d37e4e8cc187ea7666ee2e8e7768a4e0419d の修正をしてしまったのでこれを暫定対応とします。

設定の保持というのは各エディタ部分を個別にということであっていますか？
少し時間をいただきますが取り掛かってみますね。

**Comment by nomadoor** [comment]
分かりづらくて申し訳ないです。
ノードを消して新しく出したり、ComfyUIを再起動すると、MinimapやThemeの設定が戻ってしまうので、これらが変わらないようにしたいです。(保存されてたりされてなかったりするので、不安定なだけかもしれません)
[![Image from Gyazo](https://i.gyazo.com/3d7ff6c2c4b75ab82f9ee62fa31e13bd.gif)](https://gyazo.com/3d7ff6c2c4b75ab82f9ee62fa31e13bd)

**Comment by Taremin** [comment]
わざわざ動画までありがとうございます！
設定の保存自体は行っていて、ComfyUIの再起動やリロード、ノードの作成を検知したら設定を読み込むようにしているはずなのですがタイミングによっては問題が発生しているかもしれません。
（デフォルトユーザなら `ComfyUI/user/default/comfy.settings.json` をAPIから読み書きしています）
そちらも調べてみます。

**Comment by Taremin** [comment]
ご期待の修正かわかりませんが、エディタ側のコンテキストメニュー（テキスト入力欄右クリック）で各種設定を行えるようにしたのと、ヘッダを非表示にする設定を追加しました。

設定が保存されていないような挙動もおそらく修正できたと思うのですけど、不具合があったらお知らせください。

**Comment by nomadoor** [comment]
この設定の仕方は初めて見ました。面白い……
右クリックからの設定は完璧に動いてます！素晴らしい🤩

ただ設定の保存はうまくいってないようで、上で載せた動画と同じ挙動のままです。
`ComfyUI/user/default/comfy.settings.json` を覗いてみたんですがなにも書かれていませんでした。

ComfyUI manager以外カスタムノードは入れていないので、ほかに環境の違いがあるとするとポータブル版を使っていることくらいでしょうか？

**Comment by Taremin** [comment]
確認ありがとうございます！
設定部分がきちんと動いたみたいで良かったです。

設定の保存がうまくいってないとなると ComfyUI の設定を保存する API が機能していない可能性がありますね。
この機能が追加されたのが2週間ほど前（ https://github.com/comfyanonymous/ComfyUI/commit/235727fed79880ac2053a1db1b0d13c0f75714e8 ）みたいなのですが、いつのポータブル版を利用していますか？
バージョン違いもなさそうならブラウザの開発者ツールで詳しい状況を教えていただくかもしれません…
（たとえばエディタの設定を変えたときにコンソールにエラーが出てないかとか）

**Comment by nomadoor** [comment]
アップデートと念のためvenvの方でもインストールして試してみましたが同じでした。

エディタの設定を変更した際はConsoleに以下のようなエラーが表示されますが、関係ありますでしょうか？

``` console.log
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at main.bundle.js:2:191673
    at Ore.changeReplaceUnderscore (main.bundle.js:2:3401989)
    at Ore.syncReplaceUnderscore (main.bundle.js:2:3405222)
    at HTMLInputElement.toggleCallback (main.bundle.js:2:3403330)
(anonymous) @ main.bundle.js:2
changeReplaceUnderscore @ main.bundle.js:2
syncReplaceUnderscore @ main.bundle.js:2
toggleCallback @ main.bundle.js:2
```

**Comment by Taremin** [comment]
エラー内容ありがとうございます、大変たすかります。
エラー内容を見て設定を消してから確認したら再現出来ました。
設定がないときにのみ起こるバグで設定が保存できないため毎回設定の保存がエラーになっていたようです。

修正をv0.1.5としてリリースしたので確認していただけるとたすかります。

**Comment by nomadoor** [comment]
完璧に動作してます！
本当にありがとうございました🥰

**Comment by Taremin** [comment]
きちんと動いてよかったです。
こちらこそありがとうございました！
